-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-12-06 06:52:32 GMT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE class (
    module_number     CHAR(6) NOT NULL,
    module_name       VARCHAR2(20) NOT NULL,
    campus_location   VARCHAR2(10),
    room_number       CHAR(8),
    lecturer_initials VARCHAR2(4) NOT NULL,
    lecturer_name     VARCHAR2(20) NOT NULL,
    duration          VARCHAR2(10)
);

ALTER TABLE class
    ADD CONSTRAINT campus_location_value CHECK ( campus_location IN ( '', 'CHELTENHAM', 'HEREFORD', 'WARWICK' ) );

ALTER TABLE class
    ADD CONSTRAINT class_pk PRIMARY KEY ( lecturer_initials,
                                          lecturer_name,
                                          module_number,
                                          module_name );

CREATE TABLE course (
    course_code         CHAR(5) NOT NULL,
    course_name         VARCHAR2(30) NOT NULL,
    course_duration     NUMBER,
    school_abbreviation CHAR(5) NOT NULL,
    school_name         VARCHAR2(20) NOT NULL
);

ALTER TABLE course
    ADD CONSTRAINT course_duration_range CHECK ( course_duration BETWEEN 1 AND 7 );

ALTER TABLE course ADD CONSTRAINT course_pk PRIMARY KEY ( course_code,
                                                          course_name );

CREATE TABLE course_module (
    course_code   CHAR(5) NOT NULL,
    course_name   VARCHAR2(30) NOT NULL,
    module_number CHAR(6) NOT NULL,
    module_name   VARCHAR2(20) NOT NULL,
    no_of_credits NUMBER(2) NOT NULL
);

ALTER TABLE course_module
    ADD CONSTRAINT course_module_pk PRIMARY KEY ( module_number,
                                                  module_name,
                                                  course_code,
                                                  course_name );

CREATE TABLE enrolment (
    student_number     CHAR(8) NOT NULL,
    module_number      CHAR(6) NOT NULL,
    module_name        VARCHAR2(20) NOT NULL,
    period             VARCHAR2(9) NOT NULL,
    academic_year      VARCHAR2(9) NOT NULL,
    overall_percentage VARCHAR2(4)
);

ALTER TABLE enrolment
    ADD CONSTRAINT enrolment_pk PRIMARY KEY ( student_number,
                                              module_number,
                                              module_name );

CREATE TABLE lecturer (
    initials            VARCHAR2(4) NOT NULL,
    name                VARCHAR2(20) NOT NULL,
    school_abbreviation CHAR(5) NOT NULL,
    school_name         VARCHAR2(20) NOT NULL,
    date_of_birth       DATE NOT NULL,
    room_number         CHAR(8) NOT NULL,
    telephone_extension NUMBER(4) NOT NULL,
    teaching_band       NUMBER
);

ALTER TABLE lecturer
    ADD CONSTRAINT teaching_band_range CHECK ( teaching_band BETWEEN 50 AND 500 );

ALTER TABLE lecturer ADD CONSTRAINT lecturer_pk PRIMARY KEY ( initials,
                                                              name );

CREATE TABLE module (
    module_number          CHAR(6) NOT NULL,
    module_name            VARCHAR2(20) NOT NULL,
    school_abbreviation    CHAR(5) NOT NULL,
    school_name            VARCHAR2(20) NOT NULL,
    module_leader_initials VARCHAR2(4) NOT NULL,
    module_leader          VARCHAR2(20) NOT NULL
);

ALTER TABLE module ADD CONSTRAINT module_pk PRIMARY KEY ( module_number,
                                                          module_name );

CREATE TABLE registration (
    student_number CHAR(8) NOT NULL,
    course_code    CHAR(5) NOT NULL,
    course_name    VARCHAR2(30) NOT NULL,
    grade          VARCHAR2(20),
    start_date     DATE NOT NULL,
    end_date       DATE
);

ALTER TABLE registration ADD CONSTRAINT enddate_chk CHECK ( start_date < end_date );

ALTER TABLE registration
    ADD CONSTRAINT registration_pk PRIMARY KEY ( course_code,
                                                 course_name,
                                                 student_number );

CREATE TABLE school (
    school_abbreviation     CHAR(5) NOT NULL,
    school_name             VARCHAR2(20) NOT NULL,
    head_of_school_initials VARCHAR2(4) NOT NULL,
    head_of_school          VARCHAR2(20) NOT NULL
);

CREATE UNIQUE INDEX school__idx ON
    school (
        head_of_school_initials
    ASC,
        head_of_school
    ASC );

ALTER TABLE school ADD CONSTRAINT school_pk PRIMARY KEY ( school_abbreviation,
                                                          school_name );

CREATE TABLE student (
    student_number CHAR(8) NOT NULL,
    student_name   VARCHAR2(20) NOT NULL,
    email          VARCHAR2(30) NOT NULL,
    date_of_birth  DATE NOT NULL
);

ALTER TABLE student ADD CONSTRAINT student_pk PRIMARY KEY ( student_number );

ALTER TABLE class
    ADD CONSTRAINT class_lecturer_fk FOREIGN KEY ( lecturer_initials,
                                                   lecturer_name )
        REFERENCES lecturer ( initials,
                              name );

ALTER TABLE class
    ADD CONSTRAINT class_module_fk FOREIGN KEY ( module_number,
                                                 module_name )
        REFERENCES module ( module_number,
                            module_name );

ALTER TABLE course_module
    ADD CONSTRAINT course_module_course_fk FOREIGN KEY ( course_code,
                                                         course_name )
        REFERENCES course ( course_code,
                            course_name );

ALTER TABLE course_module
    ADD CONSTRAINT course_module_module_fk FOREIGN KEY ( module_number,
                                                         module_name )
        REFERENCES module ( module_number,
                            module_name );

ALTER TABLE course
    ADD CONSTRAINT course_school_fk FOREIGN KEY ( school_abbreviation,
                                                  school_name )
        REFERENCES school ( school_abbreviation,
                            school_name );

ALTER TABLE enrolment
    ADD CONSTRAINT enrolment_module_fk FOREIGN KEY ( module_number,
                                                     module_name )
        REFERENCES module ( module_number,
                            module_name );

ALTER TABLE enrolment
    ADD CONSTRAINT enrolment_student_fk FOREIGN KEY ( student_number )
        REFERENCES student ( student_number );

ALTER TABLE lecturer
    ADD CONSTRAINT lecturer_school_fk FOREIGN KEY ( school_abbreviation,
                                                    school_name )
        REFERENCES school ( school_abbreviation,
                            school_name );

ALTER TABLE module
    ADD CONSTRAINT module_lecturer_fk FOREIGN KEY ( module_leader_initials,
                                                    module_leader )
        REFERENCES lecturer ( initials,
                              name );

ALTER TABLE module
    ADD CONSTRAINT module_school_fk FOREIGN KEY ( school_abbreviation,
                                                  school_name )
        REFERENCES school ( school_abbreviation,
                            school_name );

ALTER TABLE registration
    ADD CONSTRAINT registration_course_fk FOREIGN KEY ( course_code,
                                                        course_name )
        REFERENCES course ( course_code,
                            course_name );

ALTER TABLE registration
    ADD CONSTRAINT registration_student_fk FOREIGN KEY ( student_number )
        REFERENCES student ( student_number );

ALTER TABLE school
    ADD CONSTRAINT school_lecturer_fk FOREIGN KEY ( head_of_school_initials,
                                                    head_of_school )
        REFERENCES lecturer ( initials,
                              name );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             1
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
